const SCROLL_CONTAINER_TOP = 'top'
const SCROLL_CONTAINER_BOTTOM = 'bottom'
const SCROLL_CONTAINER_TOP_RATIO = 0.398
const SCROLL_CONTAINER_BOTTOM_RATIO = 0.3

export {
  SCROLL_CONTAINER_TOP,
  SCROLL_CONTAINER_BOTTOM,
  SCROLL_CONTAINER_TOP_RATIO,
  SCROLL_CONTAINER_BOTTOM_RATIO
}